[package]
name = "fillit"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
enum-ordinalize = "3.1.9"

[profile.release]
debug = true

[profile.bench]
debug = true
